name: 'Kubectl tool installer'
description: 'Install a specific version of kubectl binary. Acceptable values are latest or any semantic version string like 1.15.0'
inputs: 
  version:
    description: 'Version of kubectl'
    required: true
    default: 'latest'
    deprecationMessage: 'This action is ARCHIVED and will not receive any updates, update your workflows to use the new action azure/setup-kubectl@v1'
outputs:
  kubectl-path:
    description: 'Path to the cached kubectl binary'
branding:
  color: 'blue'
runs:
  using: 'node12'
  main: 'lib/run.js'
